config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: "pages#home"

  resources :offices do
    resources :bookings, only: %i[index create]
    resources :office_facilities, only: %i[new create]
  end

  resources :bookings, only: %i[show destroy edit update] do
    resources :reviews, only: %i[new create]
    get "/download", to: "bookings#download"
  end

  resources :reviews, only: [:destroy]
  resources :office_facilities, only: %i[edit update destroy]

  get "/my_properties", to: "pages#my_properties", as: :my_properties
  get "/my_bookings", to: "pages#my_bookings", as: :my_bookings
  get "/my_account", to: "pages#my_account", as: :my_account
  get "/terms_and_conditions", to: "pages#terms_and_conditions"
end

app/models/office.rb
class Office < ApplicationRecord
  attr_accessor :facility

  # ASSOCIATIONS
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  # has_many :reviews, through: :bookings
  has_many :office_facilities, dependent: :destroy
  has_many :facilities, through: :office_facilities
  accepts_nested_attributes_for :office_facilities, reject_if: :all_blank, allow_destroy: true

  # VALIDATIONS
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :max_capacity, :meeting_rooms, numericality: { greater_than_or_equal_to: 0 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # NOTIFICATIONS
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy

  # SEARCH
  include PgSearch::Model

  pg_search_scope :search_by_address,
                  against: [:address],
                  using: {
                    tsearch: { prefix: true }
                  }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # attr_accessor :facility

  before_action :set_office, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @offices = policy_scope(Office).search_by_address(params[:query])
    else
      @offices = policy_scope(Office).all
    end

    @offices = @offices.where("max_capacity <= ?", params[:max_capacity]) if params[:max_capacity].present?
    @offices = @offices.where("price <= ?", params[:max_price]) if params[:max_price].present?
    @offices = @offices.where("price >= ?", params[:min_price]) if params[:min_price].present?

    # The `geocoded` scope filters only offices with coordinates
    @markers = @offices.geocoded.map do |office|
      {
        lat: office.latitude,
        lng: office.longitude,
        info_window_html: render_to_string(partial: "popup", locals: { office: }),
        image_url: helpers.asset_url("favicon.png")
      }
    end

    if params[:facilities]&.[](:facility_id).present? && params[:facilities]&.[](:facility_id) != ['']
      @offices = @offices.joins(:facilities).where(facilities: { id: params[:facilities][:facility_id].map { |e| e.to_i }}).uniq
    end

  end

  def show
    @booking = Booking.new
    @bookings = @office.bookings
    authorize @booking
    @markers = [{
      lat: @office.latitude,
      lng: @office.longitude,
      info_window_html: render_to_string(partial: "popup", locals: { office: @office }),
      image_url: helpers.asset_url("favicon.png")
    }]

    @has_review = @bookings.any? { |booking| !booking.review.nil? }
    mark_notification_as_read
  end

  def new
    @office = Office.new
    @office.office_facilities.build
    authorize @office
  end

  def create
    @office = Office.new(office_params)
    @office.user = current_user

    authorize @office
    if @office.save!
      redirect_to  office_path(@office)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @office.office_facilities.destroy_all
    # raise
    if @office.update(office_params)
      redirect_to office_path(@office), notice: "Your property's details have been successufly saved"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @office.destroy
    redirect_to my_properties_path, notice: "Property has been permanently deleted from your list"
  end

  private

  def office_params
    params.require(:office).permit(:name,
                                   :meeting_rooms,
                                   :price,
                                   :address,
                                   :description,
                                   :max_capacity,
                                   :photo,
                                   # IF WE USE QUANTITIES USE THIS ONE
                                   office_facilities_attributes: %i[_destroy facility_id quantity])
    # IF WE DON'T WANT QUANTITIES USE:
    #  facility_ids: [])
  end

  def set_office
    @office = Office.find(params[:id])
    authorize @office
  end

  def mark_notification_as_read
    if current_user
      notifications_to_mark_as_read = @office.notifications_as_office.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/views/offices/_facilities_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="row">
    <div class="col-6">
      <%= f.input :facility_id, collection: Facility.all, label_method: :name, label_value: :id, include_hidden: false, item_label_class: "ps-1" %>
    </div>
    <div class="col-2">
      <%= f.input :quantity, input_html: { min: '1', value: f.object.quantity || '1' } %>
    </div>
    <div class="col-2 align-self-center">
      <button type="button" data-action="nested-form#remove" class="btn-error mt-3" style="border-width:0px;" ><i class="fa-solid fa-x"></i></button>
    </div>
  </div>
  <%= f.hidden_field :_destroy %>
</div>

app/views/offices/_form.html.erb
  <%= simple_form_for @office, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
  <%= f.input :name %>
  <%= f.input :meeting_rooms %>
  <%= f.input :max_capacity %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :photo, as: :file %>
  <div class="d-flex flex-column mb-3">
    <template data-nested-form-target="template">
      <%= f.fields_for :office_facilities, OfficeFacility.new, child_index: 'NEW_RECORD' do |facility| %>
        <%= render "facilities_form", f: facility %>
      <% end %>
    </template>
    <%= f.fields_for :office_facilities do |facility| %>
      <%= render "facilities_form", f: facility %>
    <% end %>
    <!-- Inserted elements will be injected before that target. -->
    <div data-nested-form-target="target"></div>
    <button type="button" data-action="nested-form#add" id="add_facilities"><i class="fa-solid fa-plus"></i> Add more facilities</button>
  </div>
  <%= f.submit class: "btn-confirm-new" %>
  <%= link_to "Cancel", offices_path, style: "color:white" %>
<% end %>

app/views/offices/_marker.html.erb
<%= image_tag "favicon.png", height: 30, width: 30, alt: "Logo" %>

app/views/offices/_popup.html.erb
<p><%= office.name %></p>
<small><%= office.address %></small>

app/views/offices/edit.html.erb
<div class="container" style="width:932px;">
  <% content_for :title do %>
    <%= "Edit your MeetingSpace" %>
  <% end %>
  <h1 class=text-center>Update your property</h1>
  <div>
    <div class="form">
      <p>Make sure to regularly update your properties if there are any significant changes to your space. Make sure any information is accurate</p>
      <p>Any changes you make are instantly updated on the page</p>
      <%= render "form", office: @office %>
    </div>
  </div>
</div>

app/views/offices/index.html.erb
<% content_for :title do %>
  <%= "Look for the office which suits you the best!" %>
<% end %>
<div style="position:sticky; top:0px; background-color:#e7e7e7;">
  <div class="text-center mt-3">
    <% if params[:query].present? %>
      <h1><%= "MeetingSpaces in #{params[:query].capitalize}"%></h1>
    <% else %>
      <h1>MeetingSpaces</h1>
    <% end %>
  </div>
  <div class="container" style="display: flex !important; justify-content:center;">
    <div data-controller="map"
      id='index-map'
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-markers-value="<%= @markers.to_json %>"
      style='width: 95%; height: 300px;'>
    </div>
  </div>
  <%= form_with url: offices_path, method: :get, class: "d-flex pt-5 pb-4 justify-content-center gap-2", data: { controller: 'checkbox-select-all' } do |f| %>
    <%= f.text_field :query, value: params[:query], placeholder: "Find a Space in..." %>
    <%= f.number_field :max_price, value: params[:max_price], min: 0, placeholder: "Max €" %>
    <%= f.number_field :min_price, value: params[:min_price], min: 0, placeholder: "Min €" %>
    <%= f.number_field :max_capacity, value: params[:max_capacity], min: 0, placeholder: "Max capacity" %>
    <%= f.fields_for :facilities do |facilities_form| %>
      <div id="list1" class="dropdown-check-list" tabindex="100" data-controller="checkbox">
        <span class="anchor">
          <% if params[:facilities]&.[](:facility_id).present? %>
            <% if params[:facilities]&.[](:facility_id)&.count == 1 %>
              Choose a Facility
            <% elsif params[:facilities]&.[](:facility_id)&.count == 2 %>
              <%= "#{ params[:facilities]&.[](:facility_id)&.count - 1 } facility chosen" %>
            <% else %>
              <%= "#{ params[:facilities]&.[](:facility_id)&.count - 1 } facilities chosen" %>
            <% end %>
          <% else %>
            Choose a Facility
          <% end %>
        </span>
        <ul id="items" class="items">
          <%= facilities_form.collection_check_boxes(:facility_id, Facility.all, :id, :name, { checked: params[:facilities]&.[](:facility_id) } ) do |f| %>
            <li>
              <%= f.label %>
              <%= f.check_box %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.submit "Search", class: 'custom-button', style:"border-color:dark-gray; padding:7px; border-style:outset; border-width:2px; text-decoration:none;" %>
    <%= link_to "Clear", offices_path, style: "width: 60px; text-decoration: underline; align-self:center; color:#002B5B;" %>
  <% end %>
</div>
<div class="index-container">
  <% if @offices.empty?  %>
    <p>Opss, no Offices match your filters...</p>
  <% else  %>
    <div class="office-grid">
      <% @offices.each do |office| %>
        <div class="grid-item">
          <%= link_to office_path(office), :class => "text-decoration-none" do %>
            <div class="office-card">
              <%= cl_image_tag office.photo.key, :class => "office-card-img", crop: :fill if office.photo.attached? %>
              <div class="card-content">
                <h1 class="card-header">
                  <strong><%= office.name %></strong>
                </h1>
                <div class="card-attr">
                  <i class="fa-solid fa-person-shelter"></i>
                  <span><%= office.max_capacity %></span>
                  <i class="fa-solid fa-handshake"></i>
                  <span><%= office.meeting_rooms %></span>
                </div>
                <div class="card-price">
                  <span><%= office.price.to_i %> <%= icon('fa solid', 'euro') %> day</span>
                </div>
                <div class="card-rating">
                  <% if office.bookings.any? { |booking| !booking.review.nil? } %>
                    <% array=[] %>
                    <% office.bookings.each do |booking| %>
                      <% array.push(booking.review&.ratings) %>
                    <% end %>
                    <% if array.sum(&:to_f)/array.compact.length == 5 %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_i)/array.compact.length)}/5" %></p>
                    <% elsif array.sum(&:to_f)/array.compact.length == 4 %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_i)/array.compact.length)}/5" %></p>
                    <% elsif array.sum(&:to_f)/array.compact.length == 3 %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_i)/array.compact.length)}/5" %></p>
                    <% elsif array.sum(&:to_f)/array.compact.length == 2 %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_i)/array.compact.length)}/5" %></p>
                    <% elsif array.sum(&:to_f)/array.compact.length == 1 %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_i)/array.compact.length)}/5" %></p>
                    <% else %>
                      <p><%= icon('fa-solid', 'star') * (array.sum(&:to_i)/array.compact.length) + icon('fa-regular', 'star') * (5-array.sum(&:to_i)/array.compact.length) + " #{(array.sum(&:to_f)/array.compact.length).round(1)}/5" %></p>
                    <% end %>
                  <% else %>
                    <i class="fa-solid fa-star"></i>
                    <span><%= "Not rated yet" %></span>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end  %>
</div>

app/views/offices/new.html.erb
  <% content_for :title do %>
    <%= "List your office in MeetingSpace" %>
  <% end %>
  <div class="heading-banner">
    <h5 class="text-center">Special sign up offer - 0% commission on your first 3 bookings!</h5>
  </div>
   <div class="two-columns">
     <div class ="side-bar">
    <div class="feature-header">
    <h1 class="text-center fw-bold my-4">List your MeetingSpace today!</h1>
    <div class="feature-text">
      <h4 class="mb-4">Connect your vacant MeetingSpace with business people from around the globe looking for a place to work. With just a few clicks, you can turn your empty MeetingSpace into revenue.</h4>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      </div>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="card-white-new-1"></div>
            <div class="content">
              <h4 class="card-text mb-0 text-center"><strong>Premium users</strong><br></h4>
              <p>MeetingSpace has over 1m users seeking office space allowing you to maximise your revenue.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-white-new-2"></div>
            <div class="content">
              <h4 class="card-text mb-0 text-center"><strong>Global coverage</strong><br></h4>
              <p>MeetingSpace has users all over the world seeking office space in the city they are in.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-white-new-3"></div>
            <div class="content">
              <h4 class="card-text mb-0 text-center"><strong>24/7 support</strong><br> </h4>
              <p>Specially trained agents on hand 24/7/365 to ensure the smooth running of your office rental.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
      <div class="row">
    <div class="quote-card col-md-12">
      <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
      <div class="quote-content">
        <p><strong>Mr Rich Landlord</strong></p>
        <p>"I started renting my spare office space on MeetingSpace and now my office is full and I'm making so much extra cash each month. I love MeetingSpace"</p>
      </div>
    </div>
    </div>
    </div>
  </div>
 </div>
    <div class="form my-5">
      <h3 class="text-center">Upload your MeetingSpace</h3>
      <p>List a new space for professionals and companies to rent out.</p>
      <%= render "form", office: @office %>
    </div>
 </div>

app/views/offices/show.html.erb
<% require "date" %>
<% current_day = DateTime.current.to_date %>
<div class="show-container">
  <div class="show-office-container">
    <div class="show-office-card">
      <% content_for :title do %>
        <%= @office.name %>
      <% end %>
      <div class="d-flex justify-content-between">
        <h2 class="card-title"><strong><%= @office.name %></strong></h2>
        <div class="ratings-average">
          <% if @has_review %>
            <% array=[] %>
            <% @office.bookings.each do |booking| %>
              <% array.push(booking.review&.ratings) %>
            <% end %>
            <% if array.sum(&:to_f)/array.compact.length == 5 %>
              <p class="average"><%= "#{array.sum(&:to_i)/array.compact.length}/5" %></p>
            <% elsif array.sum(&:to_f)/array.compact.length == 4 %>
              <p class="average"><%= "#{array.sum(&:to_i)/array.compact.length}/5" %></p>
            <% elsif array.sum(&:to_f)/array.compact.length == 3 %>
              <p class="average"><%= "#{array.sum(&:to_i)/array.compact.length}/5" %></p>
            <% elsif array.sum(&:to_f)/array.compact.length == 2 %>
              <p class="average"><%= "#{array.sum(&:to_i)/array.compact.length}/5" %></p>
            <% elsif array.sum(&:to_f)/array.compact.length == 1 %>
              <p class="average"><%= "#{array.sum(&:to_i)/array.compact.length}/5" %></p>
            <% else %>
              <p class="average"><%= "#{(array.sum(&:to_f)/array.compact.length).round(1)}/5" %></p>
            <% end %>
          <% else %>
            <style type="text/css">
              .ratings-average{display:none};<%= " " %>
            </style>
          <% end %>
        </div>
      </div>
      <div class="container">
        <div class="d-flex align-items-baseline">
          <span class=""><%= icon('fa-solid', 'location-dot') %></span>
          <p class=""><%= @office.address %></p>
        </div>
      </div>
      <%= cl_image_tag @office.photo.key, width:700, crop: :fill if @office.photo.attached?%>
      <div data-controller="read-more" data-read-more-more-text-value="Read more" data-read-more-less-text-value="Read less">
        <p class="line-clamp" data-read-more-target="content">
          <%= @office.description %>
        </p>
        <div class="d-flex justify-content-start"; style="gap:10px; padding-bottom:20px;">
          <a data-action="read-more#toggle" class="text-blue" style="cursor:pointer; padding: 20px 0px 0px 20px;">Read more</a>
          <% if policy(@office).edit? %>
            <%= link_to "Edit", edit_office_path, class:"btn-edit", style:"height:40px; margin-top:10px; border-color:black; padding:7px; border-style:outset; border-width:2px; text-decoration:none;" %>
          <% end %>
          <% if policy(@office).destroy? %>
            <%= link_to "Delete your propierty", office_path(@office), class: "btn-delete", style:"height:40px; margin-top:10px; border-color:black; padding:7px; border-style:outset; border-width:2px; text-decoration:none;", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
          <% if current_user == @office.user %>
            <%= link_to "Bookings", office_bookings_path(@office), class: "btn-mint", style:"height:40px; margin-top:10px; border-color:black; padding:7px; border-style:outset; border-width:2px; text-decoration:none;" unless @bookings.empty? %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="d-flex" style="gap:100px; justify-content:center; height:10px; margin-bottom:10px;">
      <% if current_user == @office.user %>
        <h5><strong>Max capacity:</strong> <%=  @office.max_capacity%> people</h5>
        <h5><strong>Meeting rooms:</strong> <%= @office.meeting_rooms %></h5>
        <h5><strong>Price per day:</strong> <%= @office.price.to_i %>€</h5>
      <% else %>
        <h5><strong>Max capacity:</strong> <%= @office.max_capacity %> people</h5>
        <h5><strong>Meeting rooms:</strong> <%= @office.meeting_rooms %></h5>
      <% end %>
    </div>
    <% unless @office.facilities.empty? %>
      <div class="show-facilities">
        <h2 class="card-title">Facilities</h2>
        <% @office.facilities.each do |element| %>
          <% office_facility = OfficeFacility.where(office_id:@office.id, facility_id:element.id) %>
          <ul>
            <% if office_facility.first.quantity == 1 %>
              <li><%= element.name.capitalize %></li>
            <% else %>
              <li><%= "#{element.name.capitalize} (x#{office_facility.first.quantity})" %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% else %>
      <style type="text/css">
        .show-facilities{display:none};<%= " " %>
      </style>
    <% end %>
    <div data-controller="map"
      id='show-map'
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-markers-value="<%= @markers.to_json %>"
      style='width: 722px; height: 300px;'>
    </div>
    <div class="show-contact">
      <h2>Contact</h2>
      <div class="d-flex justify-content-between">
        <div class="d-flex" style="gap:20px;">
          <%= cl_image_tag @office.user.avatar.key, width: 50, height: 50, id: "miniavatar", crop: :fill if @office.user.avatar.attached? %>
          <p>If you have any questions, please contact <strong><%= "#{@office.user.first_name} #{@office.user.last_name}" %></strong>, owner</p>
        </div>
        <%= mail_to "#{(@office.user).email}", "Contact" %>
      </div>
    </div>
    <div class="show-office-reviews">
      <h2 class="card-title">Reviews</h2>
      <div class="write-review-card">
        <% past_bookings = @bookings.select { |booking| booking.end_date < current_day && booking.user == current_user && booking.review.nil?  && booking.confirmed?}%>
        <% if !past_bookings.nil? %>
          <% past_bookings.each do |booking| %>
            <% if booking.confirmed? && current_day > booking.end_date %>
              <div class="form">
                <%= simple_form_for [booking, Review.new] do |f| %>
                  <%= f.input :ratings, collection: (1..5).to_a, label: "Rate your experience from #{booking.start_date.strftime("%A, %B %e, %Y")} to #{booking.end_date.strftime("%A, %B %e, %Y")}", input_html: {data: {controller: "star-rating"}} %>
                  <%= f.input :comment %>
                  <%= f.submit "Submit review", class: "btn-confirm" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% else %>
        <% end %>
      </div>
      <% if @has_review %>
        <% @bookings.each do |booking| %>
          <% unless booking.review.nil? %>
            <div class="review-card">
              <div class="d-flex justify-content-between" style="margin-bottom:10px;">
                <div class="d-flex">
                  <%= cl_image_tag booking.user.avatar.key, width: 50, height: 50, id: "miniavatar", crop: :fill if booking.user.avatar.attached? %>
                  <p class="review-user" ><strong><%= booking.user.first_name+" "+booking.user.last_name %></strong><%= " #{booking.review&.created_at.strftime("%A, %B %e, %Y")}" %></p>
                </div>
                <span class="review-stars" style="margin-top:20px;" ><%= icon('fa-solid', 'star' ) * booking.review&.ratings + icon('fa-regular', 'star') * (5-booking.review&.ratings) %></span>
              </div>
              <div class="d-flex">
                <p><%= booking.review&.comment %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>This property does not have any reviews yet.</p>
      <% end %>
    </div>
  </div>
  <div class="show-booking">
    <% unless @office.user == current_user %>
      <div id="office-booking-dates" data-unavailable="<%= @office.unavailable_dates.to_json %>"></div>
      <%= simple_form_for [@office, @booking], data: { controller: 'flatpickr' } do |f| %>
        <div style="color:black; align-self:center; margin-top:40px;">
          <h3><strong><span id="office-price-per-day"><%= @office.price.to_int %></span>€</strong>/day</h3>
          <h5>Pick a date</h5>
        </div>
        <%= f.input :start_date, as: :string, label: false, required: true, input_html: {data: { flatpickr_target: "startDate" }, class: "range_start d-none"} %>
        <%= f.input :end_date, as: :string, label: false, required: true, input_html: {data: { flatpickr_target: "endDate" }, class: "range_end d-none"} %>
        <div style="margin-left:30px; color:black;">
          <p>Book for <span id="total-days">0</span><span id="string-days"> days</span></p>
          <p>Total cost: <span id="total-cost">0</span> €</p>
          <div class="row">
            <div class="col-1">
              <input type="checkbox" id="terms" name="terms" value="accept">
            </div>
            <div class="col-10">
              <label for="terms"> Accept our <%= link_to "Terms&Conditions", terms_and_conditions_path, data: { turbo_frame: "modal" } %></label>
            </div>
          </div>
        </div>
        <%= f.submit disabled: true, class: 'btn-confirm mt-3', id: 'submit_button' %>
        <p type="button" id="clear_button" style="width: 60px; text-decoration: underline; align-self:center; margin-bottom:20px; color:#002B5B;" title="clear" data-clear>Clear</p>
      <% end %>
    <% end %>
  </div>
</div>