config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: "pages#home"

  resources :offices do
    resources :bookings, only: %i[index create]
    resources :office_facilities, only: %i[new create]
  end

  resources :bookings, only: %i[show destroy edit update] do
    resources :reviews, only: %i[new create]
    get "/download", to: "bookings#download"
  end

  resources :reviews, only: [:destroy]
  resources :office_facilities, only: %i[edit update destroy]

  get "/my_properties", to: "pages#my_properties", as: :my_properties
  get "/my_bookings", to: "pages#my_bookings", as: :my_bookings
  get "/my_account", to: "pages#my_account", as: :my_account
  get "/terms_and_conditions", to: "pages#terms_and_conditions"
end

app/models/booking.rb
class Booking < ApplicationRecord
  # ASSOCIATIONS
  belongs_to :user
  belongs_to :office
  has_one :review, dependent: :destroy

  # VALIDATIONS
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :status, presence: true
  validate :end_date_after_start_date

  # status of booking
  enum status: { pending: 0, confirmed: 1, declined: 2 }

  # NOTIFICATIONS
  after_commit :notify_recipient, on: :create
  after_commit :notify_renter, on: :update
  has_noticed_notifications model_name: 'Notification'
  # before_destroy :cleanup_notifications

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end

  def notify_recipient
    # With office.user we deliver to the owner of the office and not the owner of the booking
    BookingNotification.with(booking: self, office: office).deliver(office.user)
  end

  def notify_renter
    BookingUpdateNotification.with(booking: self, office: office).deliver(user)
  end

  # def cleanup_notifications
  #   notifications_as_booking.destroy_all unless notifications_as_booking.nil?
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_office, only: %i[index new create revenue]

  def index
    @bookings = policy_scope(Booking)
    @cost = revenue(@office.bookings)
  end

  def show
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @booking.office = @office
    @booking.total_price = cost(@booking.start_date, @booking.end_date, @office.price)
    if @booking.save!
      redirect_to my_bookings_path
      flash[:notice] = "Your booking has been successful!"
    else
      redirect_to office_path(@office)
      flash[:alert] = "Your booking was not successful. Please try again"
    end
  end

  def edit
    @office = @booking.office
  end

  def update
    @booking.update(booking_params)
    if current_user == @booking.user
      redirect_to my_bookings_path
    elsif current_user == @booking.office.user
      redirect_to office_bookings_path(@booking.office)
    end
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path
  end

  def download
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice",
               template: "bookings/show",
               formats: [:html],
               disposition: :attachment,
               layout: 'pdf',
               encoding: "UTF-8"
      end
    end
  end

  private

  def cost(startdate, enddate, price)
    if enddate > startdate
      days = enddate - startdate
      total = days * price
    elsif enddate == startdate
      total = price
    end
    return '%.2f' % total
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def set_office
    @office = Office.find(params[:office_id])
  end

  def revenue(bookings)
    revenue = 0
    bookings.each do |booking|
      revenue += booking.total_price if booking.confirmed?
    end
    return revenue
  end
end

app/views/bookings/_form.html.erb
<div id="office-booking-dates" data-unavailable="<%= @office.unavailable_dates.to_json %>"></div>
<%= simple_form_for [@booking], data: { controller: 'flatpickr' }, method: :patch do |f| %>
  <%= f.input :start_date, as: :string, label: false, required: true, input_html: {data: { flatpickr_target: "startDate" }, class: "range_start d-none"} %>
  <%= f.input :end_date, as: :string, label: false, required: true, input_html: {data: { flatpickr_target: "endDate" }, class: "range_end d-none"} %>
  <div class="d-flex justify-content-center" style="gap:20px;">
  <%= f.submit class: "btn-confirm" %>
  <%= link_to "Cancel", my_bookings_path, style: "color:#002B5B; margin:8px 0px 0px 0px;" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div style="margin-top:20px;"">
  <% content_for :title do %>
    <%= "Edit your booking" %>
  <% end %>
</div>
<h1 class=text-center>Update your reservation for <%= @booking.office.name %></h1>
<div>
  <div class="booking-form">
    <p>Any changes to your booking may need to be approved again by the owner of the property.</p>
    <%= render "form", office: @office, booking: @booking %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="text-center my-3">
    <h1>Bookings for <%=  @office.name %></h1>
    <small><%= @office.address %></small>
    <h5>TOTAL REVENUE € <b><%= @cost %></b></h5>
  </div>

  <%# <-- This is the nav-bar menu --> %>

  <% bookings = @bookings.select { |booking| booking.office_id == @office.id } %>
  <div class="warpper">
    <input class="radio" id="one" name="group" type="radio" checked>
    <input class="radio" id="two" name="group" type="radio">
    <input class="radio" id="three" name="group" type="radio">

    <div class="tabs">
      <label class="tab" id="one-tab" for="one">Pending(<%= (bookings.select {|x| x.pending?}).count %>)</label>
      <label class="tab" id="two-tab" for="two">Confirmed(<%= (bookings.select {|x| x.confirmed?}).count %>)</label>
      <label class="tab" id="three-tab" for="three">Declined(<%= (bookings.select {|x| x.declined?}).count %>)</label>
    </div>

    <div class="panels">
      <div class="panel" id="one-panel">

        <div class="my-5">
          <div class="booking-cards">
            <% if (bookings.select {|x| x.pending?}).count == 0 %>
              <p>There are no pending bookings, yet.</p>
            <% else %>
              <% bookings.each do |booking| %>
                <% if booking.pending? %>
                  <div class="booking-card">
                    <div class="office-img">
                      <%= cl_image_tag booking.office.photo.key %>
                    </div>
                    <div class="office-details">
                      <p>Requested by <%= mail_to booking.user.email, booking.user.first_name %> <%= cl_image_tag booking.user.avatar.key, width: 70, crop: :fill, class: "rounded-circle" %></p>
                      <h5><%= link_to booking.office.name, office_path(booking.office), class: "hyperlinked-title" %> </h5>
                      <p><b>Total:</b> <%= booking.total_price.to_i %>€</p>
                      <p><b>Dates:</b> <%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                    </div>
                    <div class="office-buttons">
                      <%= simple_form_for (booking) do |f| %>
                        <%= f.input :status, as: :hidden, input_html: { value: 'confirmed'} %>
                        <%= f.submit 'Confirm', class: 'btn-confirm' %>
                      <% end %>
                      <%= simple_form_for(booking) do |f| %>
                        <%= f.input :status, as: :hidden, input_html: { value: 'declined'} %>
                        <%= f.submit 'Decline', class: 'btn-error' %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

      </div>
      <div class="panel" id="two-panel">

        <div class="my-5">
          <div class="booking-cards">
            <% if (bookings.select {|x| x.confirmed?}).count == 0 %>
              <p>There are no confirmed bookings</p>
            <% else %>
              <% bookings.each do |booking| %>
                <% if booking.confirmed? %>
                  <div class="booking-card">
                    <div class="office-img">
                      <%= cl_image_tag booking.office.photo.key %>
                    </div>
                    <div class="office-details">
                      <h5><%= link_to booking.office.name, office_path(booking.office), class: "hyperlinked-title" %> </h5>
                      <p><b>Total: </b>€<%= booking.total_price.to_i %></p>
                      <p><b>Dates: </b><%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                      <p>Reservation made by <%= booking.user.first_name %> <%= cl_image_tag booking.user.avatar.key, width: 70, crop: :fill, class: "rounded-circle" %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

      </div>
      <div class="panel" id="three-panel">

        <div class="my-5">
          <div class="booking-cards">
            <% if (bookings.select {|x| x.confirmed?}).count == 0 %>
              <p>There are no declined bookings</p>
            <% else %>
              <% bookings.each do |booking| %>
                <% if booking.declined? %>
                  <div class="booking-card">
                  <div class="office-img">
                      <%= cl_image_tag booking.office.photo.key %>
                    </div>
                    <div class="office-details">
                      <h5><%= link_to booking.office.name, office_path(booking.office), class: "hyperlinked-title" %> </h5>
                      <p><b>Total: </b>€<%= booking.total_price.to_i %></p>
                      <p><b>Dates: </b><%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                      <p>Reservation made by <%= booking.user.first_name %> <%= cl_image_tag booking.user.avatar.key, width: 70, crop: :fill, class: "rounded-circle" %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

      </div>
    </div>

  </div>

</div>

app/views/bookings/new.html.erb
<div class="show-booking">
  <% unless @office.user == current_user %>
    <%= simple_form_for [@office, @booking], data: { controller: 'flatpickr' } do |f| %>
      <%= f.input :start_date, as: :string, label: false, input_html: { data: { flatpickr_target: "startDate" }, class: "range_start d-none" } %>
      <%= f.input :end_date, as: :string, label: false, input_html: { data: { flatpickr_target: "endDate" }, class: "range_end d-none" } %>
      <%= f.submit class: "btn-confirm" %>
    <% end %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<% content_for :title do %>
  <%= "Your booking information for #{@booking.office.name}" %>
<% end %>
<% require "date" %>
<% current_day = DateTime.current.to_date %>
<div class="container background-colour-white">
  <h1 class="text-center my-2">Booking information for <%= @booking.office.name %></h1>
  <% if @booking.confirmed? %>
    <h2 class="text-center">Invoice # <%= @booking.id %></h2>
    <div class="download">
      <i class="fa-solid fa-file-pdf fa-fw"></i><%= link_to 'Download Invoice', booking_download_path(@booking, format: :pdf) %>
    </div>
  <% else %>
    <p class="text-center my-4">You can download an invoice of your booking, once it has been confirmed.</p>
  <% end %>
  <div class="empty-space">
  </div>
  <h5 class="mt-5">Owned & managed by: <%= @booking.office.user.first_name %> <%= @booking.office.user.last_name %></h5>
  <p>Thank you for booking with MeetingSpace. We hope you have enjoyed using our platform and your experience with us has been great for your professional meeting or company event</p>
  <br>
  <p>For any feedback on our website please email <a href="mailto:info@meetingspace.com"> info@meetingspace.com</a></p>
  <% if @booking.end_date < current_day && @booking.user == current_user && @booking.review.nil? && @booking.confirmed? %>
  <p>Don't forget to leave a  <%= link_to "review",  new_booking_review_path(@booking)%> on this property.</p>
  <% end %>
  <br>
  <br>
  <div class="my-2">
    <table class="GeneratedTable">
      <thead>
        <tr>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Day(s)</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody class="table-body">
        <tr>
          <td><%= @booking.start_date.strftime("%b %d, %Y") %></td>
          <td><%= @booking.end_date.strftime("%b %d, %Y") %></td>
          <% unless @booking.start_date == @booking.end_date %>
            <td><%= (@booking.end_date - @booking.start_date).to_i %></td>
          <% else %>
            <td>1</td>
          <% end %>
          <td><%= @booking.total_price.to_i %>€</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td><b>VAT</b></td>
          <td><%= (@booking.total_price.to_i*20)/100  %>€</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td><b>Total</b></td>
          <td>£<%= @booking.total_price.to_i %>€</td>
        </tr>
      </tbody>
    </table>
    <div class="empty-space">
    </div>
    <div class="text-center my-4">
      <p>You have agreed to our Terms & Conditions, which are legally binding</p>
      <div class="logo-background-booking">
        <%= image_tag "https://github.com/margeol90/meeting_space/blob/master/app/assets/images/MS%20logo.png?raw=true"%>
      </div>
      <div class="contact-info">
        <p>12, Piccadilly Circus, UK, info@meetingspace.com, Tel: + 01 234 567 88, Fax: + 01 234 567 89</p>
        <p>VAT reg. 1234 567 89</p>
      </div>
    </div>
  </div>
</div>