config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: "pages#home"

  resources :offices do
    resources :bookings, only: %i[index create]
    resources :office_facilities, only: %i[new create]
  end

  resources :bookings, only: %i[show destroy edit update] do
    resources :reviews, only: %i[new create]
    get "/download", to: "bookings#download"
  end

  resources :reviews, only: [:destroy]
  resources :office_facilities, only: %i[edit update destroy]

  get "/my_properties", to: "pages#my_properties", as: :my_properties
  get "/my_bookings", to: "pages#my_bookings", as: :my_bookings
  get "/my_account", to: "pages#my_account", as: :my_account
  get "/terms_and_conditions", to: "pages#terms_and_conditions"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <footer class="bg-light text-center text-white">
    <!-- Left -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #3b5998;"
          href="#!"
          role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>

        <!-- Twitter -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #55acee;"
          href="#!"
          role="button"
          ><i class="fab fa-twitter"></i
        ></a>

        <!-- Google -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #dd4b39;"
          href="#!"
          role="button"
          ><i class="fab fa-google"></i
        ></a>

        <!-- Instagram -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #ac2bac;"
          href="#!"
          role="button"
          ><i class="fab fa-instagram"></i
        ></a>

        <!-- Linkedin -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #0082ca;"
          href="#!"
          role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
        <!-- Github -->
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #333333;"
          href="#!"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
        <!-- Section: Social media -->
      </section>
    </div>
    <!-- Right -->
  </footer>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fa-solid fa-house me-2"></i>MeetingSpace
          </h6>
          <p>
            Designed and built with <i class="fas fa-heart"></i> at Le Wagon bootcamp by the MeetingSpace team
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Spaces
          </h6>
          <p>
            <a href="http://www.lwmeetingspace.me/offices/new" class="text-reset">Add your space</a>
          </p>
          <p>
            <a href="http://www.lwmeetingspace.me/#why-meetingspace" class="text-reset">Why MeetingSpace</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Top rated</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Stay in touch
          </h6>
          <p>
            <a href="http://www.lwmeetingspace.me/#about-us" class="text-reset">About us</a>
          </p>
          <p>
            <a href="#!" class="text-reset">FAQ</a>
          </p>
          <p>
            <a href="#!" class="text-reset">In the media</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Meet the team</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fa-solid fa-location-dot me-3"></i> 12, Piccadilly Circus, UK</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@meetingspace.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="http://lwmeetingspace.me/">MeetingSpace</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "ms_logo.svg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item" style="margin-top:auto; margin-bottom:auto;">
          <%= link_to "Our MeetingSpaces", offices_path, class: "navbar-buttons"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item" style="margin-top:auto; margin-bottom:auto;">
            <%= render "shared/notifications" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag "http://res.cloudinary.com/dcwwskoep/image/upload/v1678528702/j3hxxbinri977fofjcvt.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p><strong><%= "#{current_user.first_name} #{current_user.last_name}" %></strong></p>
              <%= link_to "My account", my_account_path, class: "dropdown-item" %>
              <%= link_to "New property", new_office_path, class: "dropdown-item" %>
              <%= link_to "My properties", my_properties_path, class: "dropdown-item" %>
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notification.html.erb
<li class="dropdown-item notification">
  <%= link_to notification.to_notification.message, notification.to_notification.url %>
</li>

app/views/shared/_notifications.html.erb
<% if current_user %>
  <% if @unread.count > 0 %>
    <a class="nav-link navbar-buttons-unread" href="#" id="navbarDropdown" style="padding: 10px 20px; margin-right: 10px;" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
        Notifications <span>(<%= @unread.count >= 9 ? "9+" : @unread.count %>)</span>
    </a>
  <% else %>
      <a class="nav-link navbar-buttons" href="#" id="navbarDropdown" style="padding: 10px 20px; margin-right: 10px;" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
        Notifications
    </a>
  <% end %>
  <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
    <% @unread.each do |notification| %>
      <%= render 'shared/notification', notification: notification %>
    <% end %>
    <% if @read.count > 0 && @unread.count > 0 %>
      <li>
        <hr class="dropdown-divider">
      </li>
    <% elsif @read.count + @unread.count == 0 %>
      <li class="dropdown-item">
        No notifications yet.
      </li>
    <% end %>
    <% @read.each do |notification| %>
      <%= render 'shared/notification', notification: notification %>
    <% end %>
  </ul>
<% end %>