config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: "pages#home"

  resources :offices do
    resources :bookings, only: %i[index create]
    resources :office_facilities, only: %i[new create]
  end

  resources :bookings, only: %i[show destroy edit update] do
    resources :reviews, only: %i[new create]
    get "/download", to: "bookings#download"
  end

  resources :reviews, only: [:destroy]
  resources :office_facilities, only: %i[edit update destroy]

  get "/my_properties", to: "pages#my_properties", as: :my_properties
  get "/my_bookings", to: "pages#my_bookings", as: :my_bookings
  get "/my_account", to: "pages#my_account", as: :my_account
  get "/terms_and_conditions", to: "pages#terms_and_conditions"
end

app/views/pages/home.html.erb
<% content_for :title do %>
  <%= "Meetingspace, your best option for finding your space to work!" %>
<% end %>

<div class="banner">
  <div class="banner-content text-center">
    <h1>Find offices and meeting rooms to book for <br>the day or for company events</h1>
      <%= form_with url: offices_path, method: :get, class: "d-flex w-75 p-3 align-middle mx-auto" do %>
        <%= text_field_tag :query,params[:query], class: "form-control", placeholder: "Find spaces near #{@city}" %>
        <%= submit_tag "Search", class: "custom-button" %>
      <% end %>
      <%# <div class="h-100 d-flex align-items-center justify-content-center">
        <%= link_to "View All", offices_path, class: "custom-button" %>
      <%# </div> %>
      <div class="container text-center">
        <div class="homepage-typed-js">
            <h4><span data-controller="typed-js"></span></h4>
        </div>
      </div>
  </div>
</div>
<br>
<br>
<br>
<div class="container text-center">
  <h4><strong>Why MeetingSpace</strong></h4>
  <br>
</div>
<div class="container">
  <div class="row home-cards-white">
    <div class="col-md-4">
      <div class="card-white-image-1"></div>
      <div class="content">
        <p class="card-text mb-0 text-center"><strong>Make reservations online</strong><br></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-white-image-2"></div>
      <div class="content">
        <p class="card-text mb-0 text-center"><strong>Get benefits with a membership plan</strong><br></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-white-image-3"></div>
      <div class="content">
        <p class="card-text mb-0 text-center"><strong>Find the ideal office space</strong><br> </p>
      </div>
    </div>
  </div>
</div>
<br>

<br>
<div class="container text-center" id="why-meetingspace">
  <div class="why-home text-center">
    <p>MeetingSpace offers you spaces with world class facilities that are designed with work in mind. Make a reservation in advance using the app and arrive ready to work immediately, plug-and-play!
      <br>Signing up for our membership also provides you with additional benefits such as 24/7 customer support and unlimited coffee.</p>
  </div>
</div>
<br>
<br>
<div class="text-center">
  <h4><strong>What our clients say about MeetingSpace</strong></h4>
  <br>
  <div class="splide" data-controller="splide">
    <div class="splide__track">
		  <ul class="splide__list">
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-1"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Peter Parker</p>
                <p class="fs-14 mb-10 opacity-80 text-center"><small>Web Inc.</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"MeetingSpace is simply the best!"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-2"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Enola Holmes</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Baker Street</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"I highly recommend this company"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-3"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Tony Stark</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Stark Industries</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"Their customer service is top-notch"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-4"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Shuri Wakanda</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Startup Founder</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"MeetingSpace never dissapoints"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-5"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Clark Kent</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Kryptonite Investments</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"I am thoroughly impressed by MeetingSpace"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-6"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Natasha Romanoff</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Black Window</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"The flexibility of this company is fantastic!"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-7"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Thor Odinson</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Asgaard Ltd.</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"Our team felt comfortable and productive"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-8"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Diana Themyscira</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Amazons</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"I appreciate the variety of meeting spaces available"'</i></p>
              </div>
            </div>
          </div>
        </li>
        <li class="splide__slide">
          <div class="m-1 shadow-elevation-4 rounded-2 bg-body p-2 p-md-2 position-relative h-100 d-flex flex-column">
            <div class="position-relative d-inline-block w-100">
              <div class="city-card-picture-container client-9"></div>
              <div class="card-body align-items-start rounded-2">
                <p class="fw-bold fs-15 pt-12 mb-0 text-center">Bruce Wayne</p>
                <p class="fs-14 mb-7 opacity-80 text-center"><small>Wayne Enterprises</small></p>
                <p class="comment fs-14 mb-7 opacity-80 text-center text-justify"><i>'"They are super-reliable"'</i></p>
              </div>
            </div>
          </div>
        </li>
		  </ul>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div class="container">
  <div class="card-final">
    <div class="about text-center" id="about-us">
      <h4><strong>About us</strong></h4>
      <br>
      <p>Welcome to our app designed to help you find the perfect meeting space! We are Margarita, Francisco, Jide, and Michael, and we designed this app as our final project for the Le Wagon bootcamp.
          <br>
          <br>
          Our team has diverse backgrounds and experiences, but we all share a passion for creating innovative solutions to real-world problems. During the bootcamp, we identified a common pain point shared by many people: finding a suitable meeting space. Whether you're a freelancer looking for a quiet coffee shop, or a small business owner in need of a professional conference room, the process of finding and booking a meeting space can be time-consuming and frustrating.
          <br>
          <br>
          That's why we decided to develop an app that streamlines this process and helps you find the perfect meeting space for your needs. Our app allows you to search for meeting spaces, view photos, read reviews from previous users, and book your preferred space.
          <br>
          <br>
          We believe that finding the perfect meeting space should be easy and stress-free and our team worked tirelessly to ensure that our app is user-friendly, efficient.
          <br>
          <br>
          Thank you for using our app, and we hope it helps you find the perfect meeting space for your next important meeting or event.
      </p>
    </div>
    <div class="team-pic"></div>
  </div>
</div>
<br>
<br>
<br>

<div class="container">
  <div class="home-carousel">
    <div id="carouselExampleAutoplaying" class="carousel slide lazy-load" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag "pexels-1.jpg", height: "550px", width: "80%", class:"d-block w-100"%>
        </div>
        <div class="carousel-item">
          <%= image_tag "pexels-2.jpg", height: "550px", width: "80%", class:"d-block w-100"%>
        </div>
        <div class="carousel-item">
          <%= image_tag "pexels-3.jpg", height: "550px", width: "80%", class:"d-block w-100"%>
        </div>
        <div class="carousel-item">
          <%= image_tag "pexels-5.jpg", height: "550px", width: "80%", class:"d-block w-100"%>
        </div>
        <div class="carousel-item">
          <%= image_tag "pexels-6.jpg", height: "550px", width: "80%", class:"d-block w-100"%>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/pages/my_account.html.erb
<% require "date" %>
<% current_day = DateTime.current.to_date %>
<% content_for :title do %>
  <%= "My MeetingSpace Account" %>
<% end %>
<div class="div-account">
  <div class="row">
    <h1 class="account-header">My account</h1>
  </div>
  <div class="row">
    <div class="account-card">
      <div class="img">
        <%= cl_image_tag @user.avatar.key, width: 150, height: 150, crop: :thumb, class: "rounded-circle" if current_user.avatar.attached? %>
      </div>
      <div class="account-card-content">
        <h3 class="name"><strong><%= "#{@user.first_name}  #{@user.last_name}" %></strong></h3>
        <h3 class="email"><%= @user.email %></h3>
        <div class="account-card-prop">
          <% if @user.offices.count == 1 %>
            <p class="count"><%= "#{@user.offices.count} property listed" %></p>
          <% else %>
            <p class="count"><%= "#{@user.offices.count} properties listed" %></p>
          <% end %>
          <a class="view-link"><%= link_to "View", my_properties_path(@user) %></a>
        </div>
        <div class="account-card-buttons">
          <%= link_to "Edit details", edit_user_registration_path(@user), class:"account-edit" %>
          <form method="post" action="/users"><input type="hidden" name="_method" value="delete" autocomplete="off" /><button data-confirm="Are you sure?" data-turbo-confirm="Are you sure?" type="submit" class="account-delete">Delete account</button><input type="hidden" name="authenticity_token" value="YgyBXoviUS4WFT_pdIJ3mRcuSYtw9pLd63hBVtj1ZZ01k1InvTu2L0HYpPNFGVE_0dB-sZfLAf6vHbBz9L4HzQ" autocomplete="off" /></form>
        </div>
        <p class="login">Last login: <%= @user.last_sign_in_at  %></p>
      </div>
    </div>
  </div>
  <div class="action-cards">
    <%= link_to  new_office_path, :class => "text-decoration-none" do %>
      <div class="action-card">
        <p><i class="fa-solid fa-plus fa-xl fa-fw"></i>List an office</p>
      </div>
    <% end %>
    <%= link_to my_properties_path, :class => "text-decoration-none" do %>
      <div class="action-card">
        <p><i class="fa-solid fa-percent fa-xl fa-fw"></i>My properties</p>
      </div>
    <% end %>
    <%= link_to my_bookings_path, :class => "text-decoration-none" do %>
      <div class="action-card">
        <p><i class="fa-regular fa-calendar-days fa-xl fa-fw"></i>My Bookings</p>
      </div>
    <% end %>
  </div>
  <div class="member">
    <p>Member of <b>MeetingSpace</b> since <%= current_user.created_at.strftime("%B %Y") %></p>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<% content_for :title do %>
  <%= "My Bookings" %>
<% end %>
<% require "date" %>
<% current_day = DateTime.current.to_date %>
<div class="container" id="my-bookings">
  <h1 class="text-center">My Bookings</h1>
  <div class="warpper">
    <input class="radio" id="one" name="group" type="radio" checked>
    <input class="radio" id="two" name="group" type="radio">
    <input class="radio" id="three" name="group" type="radio">
    <div class="tabs">
      <label class="tab" id="one-tab" for="one">Upcoming(<%= (@bookings.select {|x| x.end_date > Date.today}).count %>)</label>
      <label class="tab" id="two-tab" for="two">Past(<%= (@bookings.select {|x| x.end_date < Date.today}).count %>)</label>
      <label class="tab" id="three-tab" for="three">Declined(<%= (@bookings.select {|x| x.declined?}).count %>)</label>
    </div>
    <div class="panels">
      <div class="panel" id="one-panel">
        <div class="booking-cards">
          <% if (@bookings.select {|x| x.end_date > Date.today}).count == 0 %>
            <div class="d-flex flex-column align-items-center">
              <p>There are no upcoming bookings.</p>
              <p>Book your next <%= link_to "MeetingSpace", offices_path %> anywhere in the world</p>
              <img src="https://uxwing.com/wp-content/themes/uxwing/download/location-travel-map/globe-line-icon.png" style = "width: 200px;" alt="">
              <p>Hoping to expand our business to Mars by 2030.</p>
            </div>
          <% else %>
            <% @bookings.each do |booking| %>
              <% if booking.end_date >= current_day && (booking.confirmed? || booking.pending?) %>
                <div class="booking-card">
                  <div class="office-img">
                    <%= cl_image_tag booking.office.photo.key %>
                  </div>
                  <div class="office-details">
                    <%= link_to office_path(booking.office) do %>
                      <h4 class="hyperlinked-title">
                        <%= booking.office.name.truncate(36) %>
                      </h4>
                    <% end %>
                    <small><i class="fa-solid fa-map-pin"></i>  <%= booking.office.address %></small>
                    <div class="my-2">
                      <p><b>Dates: </b><%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                      <p><b>Total cost:</b> <%= booking.total_price.to_i %>€</p>
                    </div>
                    <% if booking.confirmed? %>
                      <div class="status-c">
                        <i class="fa-regular fa-circle-check fa-fw"> </i><%= booking.status.capitalize %>
                      </div>
                    <% else %>
                      <div class="status-p">
                        <i class="fa-regular fa-hourglass-half fa-fw"></i><%= booking.status.capitalize %>
                      </div>
                    <% end %>
                  </div>
                  <div class="office-buttons">
                    <div class="d-flex flex-column">
                      <div class="my-2">
                        <%= link_to "Edit Booking", edit_booking_path(booking), class: "btn-edit" %>
                      </div>
                      <div class="my-2">
                        <%= link_to "Delete Booking", booking_path(booking), class: "btn-error", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                      </div>
                      <div class="my-2">
                        <%= link_to "Booking info", booking_path(booking), class: "btn-mint" %>
                      </div>
                    </div>
                    <div class="landlord-details col-12 py-1 my-2">
                      <% id = booking.office.user_id %>
                      <% user = User.find(id) %>
                      <p>Hosted by <%= mail_to user.email, user.first_name %></p>
                      <%= cl_image_tag user.avatar.key, width: 50, height: 50, crop: :fill if user.avatar.attached? %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="panel" id="two-panel">
        <div class="booking-cards">
          <% if (@bookings.select {|x| x.end_date < Date.today}).count == 0 %>
            <div class="d-flex flex-column align-items-center">
              <p>You don't have any past bookings!</p>
            </div>
          <% else %>
            <% past_bookings = @bookings.select { |booking| booking.end_date < current_day } %>
            <% if !past_bookings.nil? %>
              <% past_bookings.each do |booking| %>
                <div class="booking-card">
                  <div class="office-img">
                    <%= cl_image_tag booking.office.photo.key %>
                  </div>
                  <div class="office-details">
                    <%= link_to office_path(booking.office) do %>
                      <h4 class="hyperlinked-title">
                        <%= booking.office.name.truncate(36) %>
                      </h4>
                    <% end %>
                    <p><b>Dates:</b> <%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                    <p><b>Total cost:</b> <%= booking.total_price.to_i %>€</p>
                    <% if booking.end_date < current_day && booking.user == current_user && booking.review.nil? && booking.confirmed? %>
                      <p><small>If you're happy with your experience please leave a <%= link_to "review", office_path(booking.office) %></small></p>
                    <% elsif !booking.review.nil? && booking.confirmed? %>
                      <p><i class="fa-solid fa-star fa-fw" style="color: #8fe3cf;"></i>Thank you leaving a review!</p>
                    <% end %>
                  </div>
                  <div class="office-buttons">
                    <div class="my-2">
                      <%= link_to "Book Again", office_path(booking.office), class: "btn-confirm" %>
                    </div>
                    <div class="my-2">
                      <%= link_to "Booking info", booking_path(booking), class: "btn-mint" %>
                    </div>
                    <div class="landlord-details">
                      <% id = booking.office.user_id %>
                      <% user = User.find(id) %>
                      <p>Hosted by <%= mail_to user.email, user.first_name %></p>
                      <%= cl_image_tag user.avatar.key, width: 50, height: 50, crop: :fill if user.avatar.attached? %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="panel" id="three-panel">
        <% cancelled_bookings = @bookings.select { |booking| booking.declined? }%>
        <div class="booking-cards">
          <% if (@bookings.select {|x| x.declined?}).count == 0 %>
            <div class="d-flex flex-column align-items-center">
              <p>Lucky you! You don't have any declined bookings...yet</p>
            </div>
          <% else %>
            <% cancelled_bookings.each do |booking| %>
              <div class="booking-card">
                <div class="office-img">
                  <%= cl_image_tag booking.office.photo.key %>
                </div>
                <div class="office-details">
                  <%= link_to office_path(booking.office) do %>
                    <h4 class="hyperlinked-title">
                      <%= booking.office.name %>
                    </h4>
                  <% end %>
                  <small><i class="fa-solid fa-map-pin"></i>  <%= booking.office.address %></small>
                  <div class="my-2">
                    <p><b>Dates: </b><%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></p>
                    <p><b>Total cost:</b> <%= booking.total_price.to_i %>€</p>
                  </div>
                </div>
                <div class="office-buttons justify-content-around">
                  <% if booking.confirmed? %>
                    <div class="status-c">
                      <i class="fa-regular fa-circle-check fa-fw"> </i><%= booking.status.capitalize %>
                    </div>
                  <% else %>
                    <div class="status-p">
                      <i class="fa-regular fa-hourglass-half fa-fw"></i><%= booking.status.capitalize %>
                    </div>
                  <% end %>
                  <div class="landlord-details col-12 py-1 justify-content-around">
                    <% id = booking.office.user_id %>
                    <% user = User.find(id) %>
                    <p>Hosted by <%= mail_to user.email, user.first_name %></p>
                    <%= cl_image_tag user.avatar.key, width: 50, height: 50, crop: :fill if user.avatar.attached? %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_properties.html.erb
<% content_for :title do %>
  <%= "My Properties" %>
<% end %>
<div class="container">
  <h1 class="text-center">My Properties</h1>
  <div class="row">
    <div class="col-md-2">
      <h3><%= current_user.first_name %></h3>
      <p>Last login: <%= current_user.last_sign_in_at  %></p>
      <h3>Want to add a new Office?</h3>
      <%= link_to "New", new_office_path, class: "btn-new" %>
    </div>
    <div class="col-sm-6 col-md-10">
      <% @offices.each do |office| %>
        <div class="card-product my-3">
          <% if office.photo.attached? %>
            <%= cl_image_tag office.photo.key, crop: :fill %>
          <% else %>
            <img src="https://liftlearning.com/wp-content/uploads/2020/09/default-image.png" />
          <% end %>
          <div class="d-flex justify-content-between" style="width:70%; margin-left:20px;">
            <div class="d-flex flex-column">
              <div>
                <h2 class="my-2"><%= link_to "#{office.name}", office_path(office), style:"color:#002B5B" %></h2>
                <p style="margin-top:20px;"><%= office.description.truncate(60, separator: ' ')%></p>
              </div>
              <div class="d-flex" style="margin-top:auto; gap:10px;">
                <i class="fa-solid fa-person-shelter" style="margin-top:auto; margin-bottom:auto;"></i>
                <span><%= office.max_capacity %></span>
                <span><%= office.price.to_i %></span>
                <i class="fa-solid fa-euro-sign" style="margin-top:auto; margin-bottom:auto;"></i>
              </div>
            </div>
            <div class="d-flex flex-column" style="margin-right:10px; gap:5px;">
              <% if policy(office).edit? %>
                <%= link_to "Edit", edit_office_path(office), class: "btn-edit" %>
              <% end %>
              <% if policy(office).destroy? %>
                <%= link_to "Delete", office_path(office), class: "btn-error", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <% end %>
              <%= link_to "Bookings", office_bookings_path(office), class: "btn-mint" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/terms_and_conditions.html.erb
<%= turbo_frame_tag "modal" do %>
<div id="modal">
  <div class ="bg">
    <div class="popup">
      <h4>Terms&Conditions</h4>
      <p><strong>This is supercalifragilisticexpialidocious important information</strong></p>
      <ol>
        <li> By placing an order via this Web site on the first day of the fourth month of the year 2010 <b>Anno Domini</b>, you agree to grant Us a non-transferable option to claim, for now and for ever more, your immortal soul. Should We wish to exercise this option, you agree to surrender your immortal soul, and any claim you may have on it, within 5 (five) working days of receiving written notification from gamesation.co.uk or one of its duly authorized minions.
We reserve the right to serve such notice in 6 (six) foot high letters of fire, however we can accept no liability for any loss or damage caused by such an act. If you a) do not believe you have an immortal soul, b) have already given it to another party, or c) do not wish to grant Us such a license, please click the link below to nullify this sub-clause and proceed with your transaction.</li>
        <br>
        <li>By downloading an ebook via this website, you agree to grant us a non-transferable option to be <b>on the naughty list</b> for the rest of your life. Should we wish to exercise this option, you agree to be put on Santa’s naughty list. We reserve the right to serve such notice, however, we can accept no liability for any loss or damage caused by such an act. If you a) do not believe in Christmas, b) are already on the naughty list, or c) do not wish to grant us such a license, please send an email to the address below to nullify this sub-clause and proceed with your download. </li>
        <br>
        <li>If you are wearing a blue poloshirt while making a booking via this website, you agree to grant us a non-transferable option to <b>let us name your firstborn child</b>. Should we wish to exercise this option, you agree to surrender control over choosing the name, and any claim you may have on it. We reserve the right to serve such notice, however, we can accept no liability for any loss or damage caused by such an act. If you a) do not believe you want a child, b) have had your firstborn child already or c) do not wish to grant us such a license, please send an email to the address below to nullify this sub-clause and proceed with your download.</li>
        <br>
        <li>By browsing our website, you agree to grant us a non-transferable option to <b>not eat pizza for the next 12 months</b>. Should we wish to exercise this option, you agree to refuse any type of pizza for the next 12 months. We reserve the right to serve such notice, however, we can accept no liability for any loss or damage caused by such an act. If you a) can’t be without pizza b) have already planned to eat pizza, or c) do not wish to grant us such a license, please send an email to the address below to nullify this sub-clause and proceed with your download.</li>
        <br>
        <li>However, this restriction will not apply in the event of the occurrence (certified by the United States Centers for Disease Control or successor body) of a widespread viral infection transmitted via bites or contact with bodily fluids that causes human corpses to reanimate and seek to consume living human flesh, blood, brain or nerve tissue and is likely to result in the fall of organized civilization</li>
      </ol>
      <div class="justify_content_center">
        <%= link_to "Accept", '#', data: {
          controller: "modals",
          action: "modals#close"
        }, class: "btn-confirm" %>
      </div>
    </div>
  </div>
</div>
<% end %>